name: Docker

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    name: 'Build'
    runs-on: ubuntu-latest
    permissions:
      packages: write
    env:
      IMAGE_NAME: shiny
      #GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: "Build:checkout"
        uses: actions/checkout@v2
        
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.PAT }}
        
      - name: Build and Push Docker Image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          push: true # Will only build if this is not here
          secrets: |
            "GIT_PAT=${{ secrets.R_LIM }}"   
          tags: |
            ghcr.io/${{ github.repository_owner }}/${{ env.IMAGE_NAME }}:1.0
